CREATE TABLE Realizations (realizations_id SERIAL NOT NULL, order_id int4 NOT NULL, employee_id int4 NOT NULL, deadline date, description varchar(2048), realization_status varchar(64) NOT NULL, PRIMARY KEY (realizations_id));
CREATE TABLE Address (address_id SERIAL NOT NULL, house_number varchar(8), street_name varchar(64) NOT NULL, city varchar(64) NOT NULL, state varchar(64) NOT NULL, postal_code varchar(16) NOT NULL, country varchar(64) NOT NULL, PRIMARY KEY (address_id));
CREATE TABLE Supplier (supplier_id SERIAL NOT NULL, name varchar(64) NOT NULL UNIQUE, type varchar(64), phone_number varchar(16) NOT NULL UNIQUE, NIP varchar(11) NOT NULL UNIQUE, REGON varchar(10) NOT NULL UNIQUE, fax varchar(40), is_active boolean NOT NULL, PRIMARY KEY (supplier_id));
CREATE TABLE Product (product_id SERIAL NOT NULL, category_id int4 NOT NULL, name varchar(64) NOT NULL UNIQUE, stock int4 CHECK(stock>=0), price float4 NOT NULL CHECK(price>0), weight float4 CHECK(weight>0), description varchar(1024), dimensions varchar(64), thumbnail varchar(255), PRIMARY KEY (product_id));
CREATE TABLE Category (category_id SERIAL NOT NULL, name varchar(64) NOT NULL UNIQUE, description varchar(1024), thumbnail varchar(255), PRIMARY KEY (category_id));
CREATE TABLE Invoice (invoice_id SERIAL NOT NULL, payment_id int4 NOT NULL, title varchar(64) NOT NULL, seller_registration_num varchar(64) NOT NULL, seller_vat_num varchar(64) NOT NULL, PRIMARY KEY (invoice_id));
CREATE TABLE Payment (payment_id SERIAL NOT NULL, order_id int4 NOT NULL, payment_timestamp timestamp NOT NULL, payment_method varchar(64) NOT NULL, payment_status varchar(64) NOT NULL, PRIMARY KEY (payment_id));
CREATE TABLE Discount (discount_id SERIAL NOT NULL, name varchar(64) NOT NULL UNIQUE, terms varchar(255) NOT NULL, value float4 NOT NULL CHECK(value>0), PRIMARY KEY (discount_id));
CREATE TABLE "Order Item" (order_item_id SERIAL NOT NULL, product_id int4 NOT NULL, order_id int4 NOT NULL, quantity int4 CHECK(quantity>0), PRIMARY KEY (order_item_id));
CREATE TABLE Cart (cart_id SERIAL NOT NULL, total_price float4 NOT NULL CHECK(total_price>0), total_weight float4 CHECK(total_weight>0), PRIMARY KEY (cart_id));
CREATE TABLE "Cart Item" (cart_item_id SERIAL NOT NULL, product_id int4 NOT NULL, cart_id int4 NOT NULL, quantity int4 CHECK(quantity>0), PRIMARY KEY (cart_item_id));
CREATE TABLE "User" (user_id SERIAL NOT NULL, first_name varchar(64) NOT NULL, second_name varchar(64) NOT NULL, email_address varchar(255) NOT NULL UNIQUE, login varchar(64) NOT NULL UNIQUE, password varchar(64) NOT NULL, country varchar(64) NOT NULL, gender varchar(32), phone_number varchar(16) UNIQUE, is_active boolean NOT NULL, PRIMARY KEY (user_id));
CREATE TABLE Employee (employee_id SERIAL NOT NULL, user_id int4 NOT NULL, insurance_number varchar(64) NOT NULL, bank_account_number varchar(32), employment_form varchar(64) NOT NULL, PRIMARY KEY (employee_id));
CREATE TABLE Client (client_id SERIAL NOT NULL, user_id int4 NOT NULL, loyalty_card_number varchar(64) UNIQUE, PRIMARY KEY (client_id));
CREATE TABLE "Order" (order_id SERIAL NOT NULL, discount_id int4, supplier_id int4 NOT NULL, address_id int4 NOT NULL, client_id int4, order_status varchar(64) NOT NULL, order_date date NOT NULL, additional_remarks varchar(1024), delivery_date date NOT NULL CHECK(delivery_date>=order_date), delivery_status varchar(64) NOT NULL, PRIMARY KEY (order_id));
ALTER TABLE Product ADD CONSTRAINT FKProduct928863 FOREIGN KEY (category_id) REFERENCES Category (category_id);
ALTER TABLE "Cart Item" ADD CONSTRAINT "FKCart Item198059" FOREIGN KEY (product_id) REFERENCES Product (product_id) ON DELETE CASCADE;
ALTER TABLE "Cart Item" ADD CONSTRAINT "FKCart Item512763" FOREIGN KEY (cart_id) REFERENCES Cart (cart_id) ON DELETE CASCADE;
ALTER TABLE "Order Item" ADD CONSTRAINT "FKOrder Item316932" FOREIGN KEY (product_id) REFERENCES Product (product_id) ON DELETE CASCADE;
ALTER TABLE Invoice ADD CONSTRAINT FKInvoice334146 FOREIGN KEY (payment_id) REFERENCES Payment (payment_id) ON DELETE CASCADE;
ALTER TABLE Realizations ADD CONSTRAINT FKRealizatio631995 FOREIGN KEY (employee_id) REFERENCES Employee (employee_id);
ALTER TABLE Employee ADD CONSTRAINT FKEmployee494877 FOREIGN KEY (user_id) REFERENCES "User" (user_id) ON DELETE CASCADE;
ALTER TABLE Client ADD CONSTRAINT FKClient503925 FOREIGN KEY (user_id) REFERENCES "User" (user_id) ON DELETE CASCADE;
ALTER TABLE "Order Item" ADD CONSTRAINT "FKOrder Item519191" FOREIGN KEY (order_id) REFERENCES "Order" (order_id) ON DELETE CASCADE;
ALTER TABLE Payment ADD CONSTRAINT FKPayment932667 FOREIGN KEY (order_id) REFERENCES "Order" (order_id) ON DELETE CASCADE;
ALTER TABLE Realizations ADD CONSTRAINT FKRealizatio110798 FOREIGN KEY (order_id) REFERENCES "Order" (order_id) ON DELETE CASCADE;
ALTER TABLE "Order" ADD CONSTRAINT FKOrder620497 FOREIGN KEY (discount_id) REFERENCES Discount (discount_id);
ALTER TABLE "Order" ADD CONSTRAINT FKOrder605175 FOREIGN KEY (client_id) REFERENCES Client (client_id);
ALTER TABLE "Order" ADD CONSTRAINT FKOrder860855 FOREIGN KEY (supplier_id) REFERENCES Supplier (supplier_id);
ALTER TABLE "Order" ADD CONSTRAINT FKOrder442797 FOREIGN KEY (address_id) REFERENCES Address (address_id);
